### ISSUE TITLE
Configuring Autoview for two different bots

### ISSUE THREAD

**Issue by CryptoReis** [CryptoGnome/Gnome-Alerts#2]
Suggestion for the Wiki (kudos to CryptoLAB for coming up with this):

If you have two bots running on different accounts, usually one for ETH and another for BTC, you can use Autoview to send buy signals to both accounts without the need to buy another Autoview subscription. It works as follows:

*Assuming bots for ETH and BTC*

**1.** Create the API keys for each account you want Autoview to connect to. You must end up with 4 keys: two default and two private; one for ETH and one for BTC.

**2.** Go to Autoview configuration, API settings and:

**2.1** Instead of using "*" for the API name, use ETH and copy paste the Default and Private key for ETH created in step 1. Save and test connection.
**2.2** Create a new API setting and name it BTC instead of "*" and copy paste the Default and Private key for BTC created in step 1. Save and test connection.

**3.** You then need to change your signal alerts and add the "a=" command. In the command part of each signal you want to create, you now need to do:

**3.1** Example 1: XLMBTC
a=BTC e=binance s=XLMBTC b=buy u=currency q=0.0175 t=limit p=0.75%

a=BTC e=binance s=XLMBTC b=buy delay=40 c=order

**3.2** Example 2: DGDETH
a=ETH e=binance s=DGDBTC b=buy u=currency q=0.02 t=limit p=0.75%

a=ETH e=binance s=DGDBTC b=buy delay=40 c=order

**Note:** The a=XYZ must be the name you used when creating the API's configuration on Autoview. So if you used, for example, "ETHBOT", then you must adjust to a=ETHBOT.

Hope it helps.

**Comment by clownfish44** [comment]
Thank you!
