### ISSUE TITLE
Alerts mass signal during downward trend

### ISSUE THREAD

**Issue by IAmNigh** [CryptoGnome/Gnome-Alerts#3]
Gnome-Alerts, version 2 (more pronounced on version 1) sends buy signals when during downward trends which increase the average purchase price making the purchased pair more difficult to sell in bullish markets. The script should be able to detect the trend and withhold buy payments until after the trend has readjusted.
![2018-03-27_1239](https://user-images.githubusercontent.com/37220652/37981868-da513a58-31bc-11e8-9dce-1fd93ae27063.png)

**Comment by clownfish44** [comment]
These were excellent buys! If you bought all of these you would have gotten out on the next pump... Not sure the issue with making good buys.

**Comment by IAmNigh** [comment]
How is buying 20x on a downward trend going to help you? It's just going to put you further into a hole. Please try to do a better job.

**Comment by CryptoGnome** [comment]
this can be adjusted by changing BB Length and RSI. 

Please try doing this and back testing the charts to see how it affects your buys
